CREATE TABLE maple_point_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maple_point INT NOT NULL,
    server VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE TABLE maple_boss_paryt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paryt_time TIME NOT NULL,
    paryt_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    use_at VARCHAR(2) NOT NULL
);
