CREATE TABLE maple_point_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maple_point INT NOT NULL,
    server VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE TABLE maple_boss_party (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_title VARCHAR(100) NOT NULL,
    channel_id VARCHAR(100) NOT NULL,
    party_time TIME NOT NULL,
    party_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    use_at VARCHAR(2) NOT NULL
);

CREATE TABLE maple_party_member (
  party_id BIGINT NOT NULL,
  discord_user_id VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (party_id, discord_user_id),
  FOREIGN KEY (party_id) REFERENCES maple_boss_party(id)
);